### ISSUE TITLE
Installation for OSX

### ISSUE THREAD

**Issue by pattacini** [icub-training/icub-training.github.io#1]
@svyatoslavdm asks whether it is possible to get [installation instructions for OSX ][1].

We do have instructions for OSX platforms available from our [manual][2], even though they're certainly not exhaustive to cover the whole set of topics we agreed on, especially considering Gazebo in the game.

@vtikha might help in this respect.

[1]: https://github.com/orgs/icub-training/teams/participants/discussions/1/comments/7
[2]: http://wiki.icub.org/wiki/ICub_Software_Installation

**Comment by vtikha** [comment]
Dear @svyatoslavdm,
I agree with @pattacini, you can install most things on macOS but you will have issues with Gazebo and thus will not be able to cover the whole set of topics. 
Having said that, I have just created a new page that includes instructions for macOS installation. 
The instructions are now included in the [installation page](https://github.com/icub-training/icub-training.github.io/wiki/Installation) of the wiki and more specifically [here](https://github.com/icub-training/icub-training.github.io/wiki/Installation-on-MacOS).

**Comment by svyatoslavdm** [comment]
Thanks @pattacini , @vtikha 

I'll try both types of installation to be prepared for everything :)
