### ISSUE TITLE
Docker and Gitpod

### ISSUE THREAD

**Issue by pattacini** [icub-training/icub-training.github.io#5]
@vtikha @traversaro please have a look at [**SW Installation**][1] page and report here any thought and/or comments.

In particular, I'm still undecided about the [**Gitpod infrastructure**][2] ☁
To tell that we can use it, we ought to make sure that all the tutorials/assignments we're going to give can run on Gitpod too.
I'm confident that we're ok with that, but please double-check it.

Also, we're relying on the `vvv-school` docker image as of now, which does not stick to any official distro release.
I believe that's not a real problem unless we say that we want to put forward the versioning.
In the latter case, I can conveniently generate an image here in this org.

[1]: ../wiki/SW-Installation
[2]: ../wiki/SW-Installation#-instructions-to-run-the-docker-container-on-the-web

**Comment by pattacini** [comment]
We should finalize the installation by Tue evening, I'd say, so that I can proceed with circulating the information among the participants.

**Comment by pattacini** [comment]
I have eventually provided a dedicated [docker image][1] using the `robotology-superbuild` and passing the release as a parameter of the GH Action.

The [installation guidelines][2] have been updated accordingly.

I've also started off testing my stuff: so far so good 👍🏻
But, please, proceed w/ testing your tutorials with the new docker image.

The part on Gitpod may stay there too: doesn't harm and can represent a good fallback anyway.

[1]: https://github.com/orgs/icub-training/packages/container/package/sandbox
[2]: https://github.com/icub-training/icub-training.github.io/wiki/SW-Installation#-instructions-to-run-the-docker-container-locally

**Comment by pattacini** [comment]
>I've also started off testing my stuff: so far so good 👍🏻

I can confirm that all motor-related code is working as expected ✔

**Comment by traversaro** [comment]
My doubts: 
>  Make sure that you have installed Docker correctly for your platform.

Can we link https://docs.docker.com/get-docker/ here for user with no docker installer on their machine? It may seems obvious, but in my experience better to be precise to avoid confusion in novice users.

**Comment by traversaro** [comment]
I would invert "☁ Instructions to run the Docker container on the web" and "✔ Check your installation" session. In my experience "optional" sections may be confusing to users, so it is better to keep them after the main instructions are done.

**Comment by pattacini** [comment]
All done 👍🏻

**Comment by traversaro** [comment]
At point 3, probably it is better to explicitly specify that `<container_name>` should be substituted with the name that the user prefers.

**Comment by pattacini** [comment]
Done ✔

**Comment by traversaro** [comment]
When reaching the "✔ Check your installation" section, I think the following points can be confusing:
* The previous section contain all the `docker` commands that are supposed to run on the host system, then in the "✔ Check your installation" section the commands are expected to be run inside the docker terminal, probably it could make sense to specify it
* Not sure if it is a problem on my system, but copy&paste from the host system to the VNC system does not work, so we could suggest the best way for the user to copy&paste the code in the "✔ Check your installation" section in the container terminal, for example opening a browser with the same page in the container.

**Comment by pattacini** [comment]
I think it's a bit clearer now:
https://github.com/icub-training/icub-training.github.io/wiki/SW-Installation#-check-your-installation.

**Comment by traversaro** [comment]
Perfect! I also tested YARP tutorials and they are working fine.

**Comment by pattacini** [comment]
@traversaro @vtikha one thing that may happen to the docker desktop GUI is that, for a weird reason that I haven't looked at yet, the X11 layer crashes somehow after a random lapse of inactivity, which is still quite long, usually.

To reinstate it, it suffices launching `start-vnc-session.sh` again.

(Actually, I don't know exactly if it crashes or there's a hidden nasty timeout somewhere)

**Comment by pattacini** [comment]
All done ✔
